modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"

[[mods]]
modId = "resourcefultrees"
version = "1.18.2-0.0.1"
displayName = "Resourceful Trees"
logoFile = "resourcefultrees.png"
credits = ""
authors = "Zerdstone"
description = '''
'''

[[dependencies.resourcefultrees]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resourcefultrees]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
